version: '2'
services:
    kemmon-app:
        image: kemmon
        external_links:
            - kemmon-mysql:mysql
            - kemmon-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kemmon?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    kemmon-mysql:
        extends:
            file: mysql.yml
            service: kemmon-mysql
    kemmon-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: kemmon-elasticsearch
